### ISSUE TITLE
3.2,3.4,4.1的下載鏈接補充

### ISSUE THREAD

**Issue by DuolaD** [360NENZ/GI-Download-Library#4]
英雄形態的哆啦D夢|DuolaD登場！

有一些不是很全，我盡我自己最大努力找全了。
記得在Readme.md裏寫一下"Provide By [哆啦D夢|DuolaD](https://github.com/DuolaD)和[CYTeam](https://www.cyteam.cn/)"
因爲是他們的微軟開發者域。

## 

GI 3.2 PC：

Audio Download Link：
[Chinese](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EXRau5gGyR1AvYSct4P2uHcBhDCWAjufOw8dzvOCQXdEBw?e=cTarxU)
[English](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EQyyI1yn95lHlH34pkLuN7ABvluNlfCwcZDdO5TOTNd86w?e=C6hkcT)
[Japanese](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EaAf2hLNnzJAmkPRVddfBkABZnI9ZN3vhNDEMZA0grRFyg?e=z5MYX1)
[Korean](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ERnAIk4TuhFIoKncZtZcw2YB7DduUYclAIxe3qhzwITw5g?e=grsSkd)

Cliect Download Link：
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EVzfvgKgm9lOtQ58P6admHUBhiHEkMGcnW0-dk_Jl_gDMA?e=IeFRdN)
[OS](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EUYdQh7ZgDJEkJhYbQDlMFYBJ7IFvHTJYHVwpfRlZpa6Tg?e=9RJu8u)

## 

GI 3.4 PC：

Audio Download Link：
[Chinese](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EVxgAbxbIqJLrzPcZsyjb1gBG4Bg6n8iPlyp2JjQxxnDTg?e=yQavKO)

Cliect Download Link：
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ESessSzjvZZIonHrtB3WumMBBP5vepOPLIrRXXcdyLnPvA?e=CWYxcG)

## 

GI 4.1 PC:

Cliect Download Link：
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EV_M-QBVF0xEv7i8yO0LzXEBdlFXQmG64WiEdFS3NdUCaA?e=UVM248)

[OS Full](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EdNr8Q0RLxBKgnL6fgWicBsB6a4bacav50yBWgGJmdA6gA?e=nsPaWw)
[OS Part 1](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ETrkBqobmHJEnRQbPLMufnIBDG52QYJTqcqfGn6_KZmXqA?e=hHfNvi)
[OS Part 2](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EeMdzjqIfkFGuv6WHoC3l8YB0DhKdxXtvQh9T0tMxzREQg?e=uhw1TZ)
[OS Part 3](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EY9RxH4gw1VIlgpqBA_6xfgBarbHlK_miE1E5r5TRxxXrg?e=4ZeF5o)
[OS Part 4](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EakwuArBC8JFix3cSCWfamUByEMe-RK6ki3eCmPhN2YSsQ?e=oDblxz)
[OS Part 5](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EcKX8hT5rs1Eskn6PuMIVvoB-npZAmYoHbM2UeVpyqKjPQ?e=D4ypne)
[OS Part 6](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EWoZYclEC0xIh18dIjlVQnsB0jZ8_O9bHsYiHgu6wE8N_g?e=d5JhKD)
[OS Part 7](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EVI4xTG2755Jp0jWBQ4gurABF5-PYMIQLZtapzbvqiEX6Q?e=K6RGik)

## 

另外据測試GI 4.1官方下載鏈接現已重新運行。
這些都是我一個個找資源然後下好上傳的QAQ

**Comment by 360NENZ** [comment]
其實你可以pr，還能混個contributor（）

**Comment by DuolaD** [comment]
> 其實你可以pr，還能混個contributor（）

我一開始沒想到這個（）
鏈接寫好了，寫到一半手滑直接Commit了

**Comment by DuolaD** [comment]
懶得搞了，你寫一下就行（）
我現在和琳妮特都是發燒+重感冒（）

**Comment by 360NENZ** [comment]
這些語音包都是CN的嗎（）

**Comment by DuolaD** [comment]
> 這些語音包都是CN的嗎（）

不知道（）

理論上應該是把‘YuanShen_Data’改成‘GenshinImpact_Data’改個名就是通用的（）

**Comment by 360NENZ** [comment]
done
